name: Create a new wpbr-ip-check release
on:
  release:
    types: [published]
jobs:
  tag:
    name: New Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          composer update --no-dev --optimize-autoloader
          mkdir build
      - name: Create artifact
        uses: montudor/action-zip@v1
        with:
          args: zip -X -r build/wpbr-ip-check.zip . -x *.git* node_modules/\* .* "*/\.*" *.dist grumphp.yml composer.* build**
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wpbr-ip-check.zip
          path: build/wpbr-ip-check.zip
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: build/wpbr-ip-check.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
